# Generated by Django 2.2 on 2021-01-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='postContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
