# Generated by Django 2.1.5 on 2021-01-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210111_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='postTitle',
            field=models.CharField(max_length=240),
        ),
    ]
