# Generated by Django 2.1.5 on 2021-01-12 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210112_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-update_stamp', '-time_stamp']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_stamp',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='update_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 12, 19, 38, 23, 512398, tzinfo=utc), null=True),
        ),
    ]
